spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # Add this to allow the H2 console frame to render
  security:
    headers:
      frame:
        options: SAMEORIGIN